<a href="https://colab.research.google.com/github/Sajib1099/Capstone-Project/blob/main/dataset_identify.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [3]:
file_path=("/content/drive/MyDrive/Thesis Dataset")

In [4]:
import pandas as pd

student_info = pd.read_csv(file_path+'/studentInfo.csv')
student_assessment = pd.read_csv(file_path+'/studentAssessment.csv')
assessments = pd.read_csv(file_path+'/assessments.csv')

In [5]:
print(student_info.shape)
print(student_assessment.shape)
print(assessments.shape)


print(student_info.columns)
print(student_assessment.columns)
print(assessments.columns)

(32593, 12)
(173912, 5)
(206, 6)
Index(['code_module', 'code_presentation', 'id_student', 'gender', 'region',
       'highest_education', 'imd_band', 'age_band', 'num_of_prev_attempts',
       'studied_credits', 'disability', 'final_result'],
      dtype='object')
Index(['id_assessment', 'id_student', 'date_submitted', 'is_banked', 'score'], dtype='object')
Index(['code_module', 'code_presentation', 'id_assessment', 'assessment_type',
       'date', 'weight'],
      dtype='object')

In [6]:
student_assessment.head()
student_assessment.head()
assessments.head()

  code_module code_presentation  id_assessment assessment_type date  weight
0         AAA             2013J           1752             TMA   19    10.0
1         AAA             2013J           1753             TMA   54    20.0
2         AAA             2013J           1754             TMA  117    20.0
3         AAA             2013J           1755             TMA  166    20.0
4         AAA             2013J           1756             TMA  215    30.0

In [7]:
student_vle = pd.read_csv(file_path + '/studentVle.csv')

print(student_vle.shape)
print(student_vle.columns)
student_vle.head()

(10655280, 6)
Index(['code_module', 'code_presentation', 'id_student', 'id_site', 'date',
       'sum_click'],
      dtype='object')

  code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1

In [8]:
student_registration = pd.read_csv(file_path + '/studentRegistration.csv')

vle = pd.read_csv(file_path + '/vle.csv')

print(student_registration.shape)
print(student_registration.columns)

print(vle.shape)
print(vle.columns)

(32593, 5)
Index(['code_module', 'code_presentation', 'id_student', 'date_registration',
       'date_unregistration'],
      dtype='object')
(6364, 6)
Index(['id_site', 'code_module', 'code_presentation', 'activity_type',
       'week_from', 'week_to'],
      dtype='object')

In [9]:
courses = pd.read_csv(file_path + '/courses.csv')
vle = pd.read_csv(file_path + '/vle.csv')

print("Courses:")
print(courses.shape)
print(courses.columns)

print("\nVLE:")
print(vle.shape)
print(vle.columns)

Courses:
(22, 3)
Index(['code_module', 'code_presentation', 'module_presentation_length'], dtype='object')

VLE:
(6364, 6)
Index(['id_site', 'code_module', 'code_presentation', 'activity_type',
       'week_from', 'week_to'],
      dtype='object')

In [10]:
print("Student Info")
print(student_info.info())

print("\nStudent Assessment")
print(student_assessment.info())

print("\nAssessments")
print(assessments.info())

print("\nStudent VLE")
print(student_vle.info())

Student Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   code_module           32593 non-null  object
 1   code_presentation     32593 non-null  object
 2   id_student            32593 non-null  int64
 3   gender                32593 non-null  object
 4   region                32593 non-null  object
 5   highest_education     32593 non-null  object
 6   imd_band              32593 non-null  object
 7   age_band              32593 non-null  object
 8   num_of_prev_attempts  32593 non-null  int64
 9   studied_credits       32593 non-null  int64
 10  disability            32593 non-null  object
 11  final_result          32593 non-null  object
dtypes: int64(3), object(9)
memory usage: 3.0+ MB
None

Student Assessment
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173912 entries, 0 to 173911
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id_assessment   173912 non-null  int64
 1   id_student      173912 non-null  int64
 2   date_submitted  173912 non-null  int64
 3   is_banked       173912 non-null  int64
 4   score           173912 non-null  object
dtypes: int64(4), object(1)
memory usage: 6.6+ MB
None

Assessments
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   code_module        206 non-null    object
 1   code_presentation  206 non-null    object
 2   id_assessment      206 non-null    int64
 3   assessment_type    206 non-null    object
 4   date               206 non-null    object
 5   weight             206 non-null    float64
dtypes: float64(1), int64(1), object(4)
memory usage: 9.8+ KB
None

Student VLE
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10655280 entries, 0 to 10655279
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   code_module        object
 1   code_presentation  object
 2   id_student         int64
 3   id_site            int64
 4   date               int64
 5   sum_click          int64
dtypes: int64(4), object(2)
memory usage: 487.8+ MB
None

In [11]:
vle['activity_type'].value_counts()
student_vle['sum_click'].describe()
student_assessment['score'].describe()
assessments['assessment_type'].value_counts()
student_info['final_result'].value_counts()

final_result
Pass           12361
Withdrawn      10156
Fail            7052
Distinction     3024
Name: count, dtype: int64

In [12]:
student_info['final_result'].value_counts()

final_result
Pass           12361
Withdrawn      10156
Fail            7052
Distinction     3024
Name: count, dtype: int64

In [13]:
assessments['assessment_type'].value_counts()

assessment_type
TMA     106
CMA      76
Exam     24
Name: count, dtype: int64

In [14]:
student_assessment['score'].describe()

count     173912
unique       102
top          100
freq       18813
Name: score, dtype: object

In [15]:
student_vle['sum_click'].describe()

count    1.065528e+07
mean     3.716946e+00
std      8.849047e+00
min      1.000000e+00
25%      1.000000e+00
50%      2.000000e+00
75%      3.000000e+00
max      6.977000e+03
Name: sum_click, dtype: float64

In [16]:
vle['activity_type'].value_counts()

activity_type
resource          2660
subpage           1055
oucontent          996
url                886
forumng            194
quiz               127
page               102
oucollaborate       82
questionnaire       61
ouwiki              49
dataplus            28
externalquiz        26
homepage            22
glossary            21
ouelluminate        21
dualpane            20
repeatactivity       5
htmlactivity         4
sharedsubpage        3
folder               2
Name: count, dtype: int64

In [17]:
assessment_data = student_assessment.merge(
    assessments,
    on='id_assessment',
    how='left'
)

print(assessment_data.shape)
assessment_data.head()

(173912, 10)

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight
0,1752,11391,18,0,78,AAA,2013J,TMA,19,10.0
1,1752,28400,22,0,70,AAA,2013J,TMA,19,10.0
2,1752,31604,17,0,72,AAA,2013J,TMA,19,10.0
3,1752,32885,26,0,69,AAA,2013J,TMA,19,10.0
4,1752,38053,19,0,79,AAA,2013J,TMA,19,10.0

In [18]:
assessment_data.columns

Index(['id_assessment', 'id_student', 'date_submitted', 'is_banked', 'score',
       'code_module', 'code_presentation', 'assessment_type', 'date',
       'weight'],
      dtype='object')

In [19]:
assessment_data['assessment_type'].value_counts()

assessment_type
TMA     98426
CMA     70527
Exam     4959
Name: count, dtype: int64

In [20]:
assessment_data.groupby('assessment_type')['score'].count()

assessment_type
CMA     70527
Exam     4959
TMA     98426
Name: score, dtype: int64

In [21]:
print(assessment_data['score'].dtype)
print(assessment_data['score'].head())

object
0    78
1    70
2    72
3    69
4    79
Name: score, dtype: object

In [22]:
assessment_data['score'] = pd.to_numeric(
    assessment_data['score'],
    errors='coerce'
)

In [23]:
assessment_data.groupby('assessment_type')['score'].mean()

assessment_type
CMA     81.027053
Exam    65.572898
TMA     72.563392
Name: score, dtype: float64

In [24]:
assessment_features = assessment_data.groupby('id_student').agg(
    avg_score=('score', 'mean'),
    total_assessments=('score', 'count')
).reset_index()

print(assessment_features.shape)
assessment_features.head()

(23369, 3)

   id_student  avg_score  total_assessments
0        6516  61.800000                  5
1        8462  87.000000                  7
2       11391  82.000000                  5
3       23629  82.500000                  4
4       23698  74.444444                  9

In [25]:
learning_features = student_vle.groupby('id_student').agg(
    total_clicks=('sum_click', 'sum'),
    active_days=('date', 'nunique')
).reset_index()

print(learning_features.shape)
learning_features.head()

(26074, 3)

   id_student  total_clicks  active_days
0        6516          2791          159
1        8462           656           56
2       11391           934           40
3       23629           161           16
4       23698           910           70

In [26]:
final_data = student_info.merge(
    assessment_features,
    on='id_student',
    how='left'
)

final_data = final_data.merge(
    learning_features,
    on='id_student',
    how='left'
)

print(final_data.shape)
final_data.head()

(32593, 16)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,avg_score,total_assessments,total_clicks,active_days
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass,82.0,5.0,934.0,40.0
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass,66.4,5.0,1435.0,80.0
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn,NaN,NaN,281.0,12.0
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass,76.0,5.0,2158.0,123.0
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass,54.4,5.0,1034.0,70.0

In [27]:
assessment_features = assessment_data.groupby(
    ['code_module', 'code_presentation', 'id_student']
).agg(
    avg_score=('score', 'mean'),
    total_assessments=('score', 'count')
).reset_index()

print(assessment_features.shape)
assessment_features.head()

(25843, 5)

  code_module code_presentation  id_student  avg_score  total_assessments
0         AAA             2013J       11391       82.0                  5
1         AAA             2013J       28400       66.4                  5
2         AAA             2013J       31604       76.0                  5
3         AAA             2013J       32885       54.4                  5
4         AAA             2013J       38053       68.0                  5

In [28]:
learning_features = student_vle.groupby(
    ['code_module', 'code_presentation', 'id_student']
).agg(
    total_clicks=('sum_click', 'sum'),
    active_days=('date', 'nunique')
).reset_index()

print(learning_features.shape)
learning_features.head()

(29228, 5)

  code_module code_presentation  id_student  total_clicks  active_days
0         AAA             2013J       11391           934           40
1         AAA             2013J       28400          1435           80
2         AAA             2013J       30268           281           12
3         AAA             2013J       31604          2158          123
4         AAA             2013J       32885          1034           70

In [29]:
final_data = student_info.merge(
    assessment_features,
    on=['code_module', 'code_presentation', 'id_student'],
    how='left'
)

final_data = final_data.merge(
    learning_features,
    on=['code_module', 'code_presentation', 'id_student'],
    how='left'
)

print(final_data.shape)
final_data.head()

(32593, 16)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,avg_score,total_assessments,total_clicks,active_days
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass,82.0,5.0,934.0,40.0
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass,66.4,5.0,1435.0,80.0
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn,NaN,NaN,281.0,12.0
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass,76.0,5.0,2158.0,123.0
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass,54.4,5.0,1034.0,70.0

In [30]:
print(final_data.isnull().sum())

code_module                0
code_presentation          0
id_student                 0
gender                     0
region                     0
highest_education          0
imd_band                   0
age_band                   0
num_of_prev_attempts       0
studied_credits            0
disability                 0
final_result               0
avg_score               6773
total_assessments       6750
total_clicks            3365
active_days             3365
dtype: int64

In [31]:
print(final_data[['avg_score', 'total_assessments',
                  'total_clicks', 'active_days']].isnull().sum())

avg_score            6773
total_assessments    6750
total_clicks         3365
active_days          3365
dtype: int64

In [32]:
print(final_data.duplicated(
    ['code_module', 'code_presentation', 'id_student']
).sum())

0

In [33]:
final_data[final_data['avg_score'].isna()]['final_result'].value_counts()

final_result
Withdrawn    5483
Fail         1287
Pass            3
Name: count, dtype: int64

In [34]:
final_data[final_data['total_clicks'].isna()]['final_result'].value_counts()

final_result
Withdrawn    2988
Fail          374
Pass            3
Name: count, dtype: int64

In [35]:
final_data.groupby('final_result')[['avg_score', 'total_clicks']].apply(
    lambda x: x.isna().sum()
)

              avg_score  total_clicks
final_result
Distinction           0             0
Fail               1287           374
Pass                  3             3
Withdrawn          5483          2988

In [36]:
courses.head(10)

  code_module code_presentation  module_presentation_length
0         AAA             2013J                         268
1         AAA             2014J                         269
2         BBB             2013J                         268
3         BBB             2014J                         262
4         BBB             2013B                         240
5         BBB             2014B                         234
6         CCC             2014J                         269
7         CCC             2014B                         241
8         DDD             2013J                         261
9         DDD             2014J                         262

In [37]:
assessments[['code_module', 'code_presentation', 'assessment_type', 'date', 'weight']].head(20)

   code_module code_presentation assessment_type date  weight
0          AAA             2013J             TMA   19    10.0
1          AAA             2013J             TMA   54    20.0
2          AAA             2013J             TMA  117    20.0
3          AAA             2013J             TMA  166    20.0
4          AAA             2013J             TMA  215    30.0
5          AAA             2013J            Exam    ?   100.0
6          AAA             2014J             TMA   19    10.0
7          AAA             2014J             TMA   54    20.0
8          AAA             2014J             TMA  117    20.0
9          AAA             2014J             TMA  166    20.0
10         AAA             2014J             TMA  215    30.0
11         AAA             2014J            Exam    ?   100.0
12         BBB             2013B             CMA   54     1.0
13         BBB             2013B             CMA   89     1.0
14         BBB             2013B             CMA  124     1.0
15         BBB             2013B             CMA  159     1.0
16         BBB             2013B             CMA  187     1.0
17         BBB             2013B             TMA   19     5.0
18         BBB             2013B             TMA   47    18.0
19         BBB             2013B             TMA   89    18.0

In [38]:
assessment_data.groupby('assessment_type')['score'].agg(
    ['count', 'mean', 'min', 'max']
)

                 count       mean  min    max
assessment_type
CMA              70527  81.027053  0.0  100.0
Exam              4959  65.572898  0.0  100.0
TMA              98253  72.563392  0.0  100.0

In [39]:
assessment_data.groupby('assessment_type')['date_submitted'].describe()

,count,mean,std,min,25%,50%,75%,max
assessment_type,,,,,,,,
CMA,70527.0,138.753626,71.582048,-8.0,69.0,147.0,208.0,608.0
Exam,4959.0,238.483565,5.717577,229.0,234.0,241.0,243.0,285.0
TMA,98426.0,93.583037,61.044593,-11.0,40.0,89.0,146.0,274.0

In [42]:
assessment_timeline = assessments[
    assessments['assessment_type'] != 'Exam'
].groupby(
    ['code_module', 'code_presentation']
)['date'].agg(['min', 'max', 'count']).reset_index()

print(assessment_timeline)

   code_module code_presentation  min max  count
0          AAA             2013J  117  54      5
1          AAA             2014J  117  54      5
2          BBB             2013B  124  89     11
3          BBB             2013J  131  96     11
4          BBB             2014B  117  82     11
5          BBB             2014J  110  54      5
6          CCC             2014B  102  67      8
7          CCC             2014J  109  67      8
8          DDD             2013B  114  81     13
9          DDD             2013J  123  88      6
10         DDD             2014B  116  74      6
11         DDD             2014J  111  62      6
12         EEE             2013J  124  68      4
13         EEE             2014B  117  68      4
14         EEE             2014J  131  68      4
15         FFF             2013B  131  89     12
16         FFF             2013J  131  96     12
17         FFF             2014B  129  87     12
18         FFF             2014J  136  94     12
19         GGG             2013J  124  61      9
20         GGG             2014B  117  61      9
21         GGG             2014J  124  61      9

In [43]:
assessment_timeline.merge(
    courses,
    on=['code_module', 'code_presentation'],
    how='left'
)

   code_module code_presentation  min max  count  module_presentation_length
0          AAA             2013J  117  54      5                         268
1          AAA             2014J  117  54      5                         269
2          BBB             2013B  124  89     11                         240
3          BBB             2013J  131  96     11                         268
4          BBB             2014B  117  82     11                         234
5          BBB             2014J  110  54      5                         262
6          CCC             2014B  102  67      8                         241
7          CCC             2014J  109  67      8                         269
8          DDD             2013B  114  81     13                         240
9          DDD             2013J  123  88      6                         261
10         DDD             2014B  116  74      6                         241
11         DDD             2014J  111  62      6                         262
12         EEE             2013J  124  68      4                         268
13         EEE             2014B  117  68      4                         241
14         EEE             2014J  131  68      4                         269
15         FFF             2013B  131  89     12                         240
16         FFF             2013J  131  96     12                         268
17         FFF             2014B  129  87     12                         241
18         FFF             2014J  136  94     12                         269
19         GGG             2013J  124  61      9                         261
20         GGG             2014B  117  61      9                         241
21         GGG             2014J  124  61      9                         269

In [45]:
timeline = assessment_timeline.merge(
    courses,
    on=['code_module', 'code_presentation'],
    how='left'
)

timeline['cutoff_day'] = (
    timeline['module_presentation_length'] * 0.5
)

print(timeline)

   code_module code_presentation  min max  count  module_presentation_length  \
0          AAA             2013J  117  54      5                         268
1          AAA             2014J  117  54      5                         269
2          BBB             2013B  124  89     11                         240
3          BBB             2013J  131  96     11                         268
4          BBB             2014B  117  82     11                         234
5          BBB             2014J  110  54      5                         262
6          CCC             2014B  102  67      8                         241
7          CCC             2014J  109  67      8                         269
8          DDD             2013B  114  81     13                         240
9          DDD             2013J  123  88      6                         261
10         DDD             2014B  116  74      6                         241
11         DDD             2014J  111  62      6                         262
12         EEE             2013J  124  68      4                         268
13         EEE             2014B  117  68      4                         241
14         EEE             2014J  131  68      4                         269
15         FFF             2013B  131  89     12                         240
16         FFF             2013J  131  96     12                         268
17         FFF             2014B  129  87     12                         241
18         FFF             2014J  136  94     12                         269
19         GGG             2013J  124  61      9                         261
20         GGG             2014B  117  61      9                         241
21         GGG             2014J  124  61      9                         269

    cutoff_day
0        134.0
1        134.5
2        120.0
3        134.0
4        117.0
5        131.0
6        120.5
7        134.5
8        120.0
9        130.5
10       120.5
11       131.0
12       134.0
13       120.5
14       134.5
15       120.0
16       134.0
17       120.5
18       134.5
19       130.5
20       120.5
21       134.5

In [48]:
timeline = assessment_timeline.merge(
    courses,
    on=['code_module', 'code_presentation'],
    how='left'
)

timeline['cutoff_day'] = (
    pd.to_numeric(timeline['module_presentation_length']) * 0.5
)

print(timeline)

   code_module code_presentation  min max  count  module_presentation_length  \
0          AAA             2013J  117  54      5                         268
1          AAA             2014J  117  54      5                         269
2          BBB             2013B  124  89     11                         240
3          BBB             2013J  131  96     11                         268
4          BBB             2014B  117  82     11                         234
5          BBB             2014J  110  54      5                         262
6          CCC             2014B  102  67      8                         241
7          CCC             2014J  109  67      8                         269
8          DDD             2013B  114  81     13                         240
9          DDD             2013J  123  88      6                         261
10         DDD             2014B  116  74      6                         241
11         DDD             2014J  111  62      6                         262
12         EEE             2013J  124  68      4                         268
13         EEE             2014B  117  68      4                         241
14         EEE             2014J  131  68      4                         269
15         FFF             2013B  131  89     12                         240
16         FFF             2013J  131  96     12                         268
17         FFF             2014B  129  87     12                         241
18         FFF             2014J  136  94     12                         269
19         GGG             2013J  124  61      9                         261
20         GGG             2014B  117  61      9                         241
21         GGG             2014J  124  61      9                         269

    cutoff_day
0        134.0
1        134.5
2        120.0
3        134.0
4        117.0
5        131.0
6        120.5
7        134.5
8        120.0
9        130.5
10       120.5
11       131.0
12       134.0
13       120.5
14       134.5
15       120.0
16       134.0
17       120.5
18       134.5
19       130.5
20       120.5
21       134.5

In [49]:
early_assessments = assessment_data.merge(
    timeline[['code_module', 'code_presentation', 'cutoff_day']],
    on=['code_module', 'code_presentation'],
    how='left'
)

early_assessments = early_assessments[
    early_assessments['date_submitted'] <= early_assessments['cutoff_day']
]

print(early_assessments.shape)
early_assessments.head()

(97489, 11)

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,cutoff_day
0,1752,11391,18,0,78.0,AAA,2013J,TMA,19,10.0,134.0
1,1752,28400,22,0,70.0,AAA,2013J,TMA,19,10.0,134.0
2,1752,31604,17,0,72.0,AAA,2013J,TMA,19,10.0,134.0
3,1752,32885,26,0,69.0,AAA,2013J,TMA,19,10.0,134.0
4,1752,38053,19,0,79.0,AAA,2013J,TMA,19,10.0,134.0

In [50]:
early_assessment_features = early_assessments.groupby(
    ['code_module', 'code_presentation', 'id_student']
).agg(
    early_avg_score=('score', 'mean'),
    early_assessment_count=('score', 'count')
).reset_index()

print(early_assessment_features.shape)
early_assessment_features.head()

(25809, 5)

,code_module,code_presentation,id_student,early_avg_score,early_assessment_count
0,AAA,2013J,11391,81.000000,3
1,AAA,2013J,28400,69.333333,3
2,AAA,2013J,31604,72.333333,3
3,AAA,2013J,32885,54.000000,3
4,AAA,2013J,38053,74.000000,3

In [51]:
early_vle = student_vle.merge(
    timeline[['code_module', 'code_presentation', 'cutoff_day']],
    on=['code_module', 'code_presentation'],
    how='left'
)

early_vle = early_vle[
    early_vle['date'] <= early_vle['cutoff_day']
]

print(early_vle.shape)
early_vle.head()

(6873886, 7)

,code_module,code_presentation,id_student,id_site,date,sum_click,cutoff_day
0,AAA,2013J,28400,546652,-10,4,134.0
1,AAA,2013J,28400,546652,-10,1,134.0
2,AAA,2013J,28400,546652,-10,1,134.0
3,AAA,2013J,28400,546614,-10,11,134.0
4,AAA,2013J,28400,546714,-10,1,134.0

In [53]:
early_learning_features = early_vle.groupby(
    ['code_module', 'code_presentation', 'id_student']
).agg(
    early_total_clicks=('sum_click', 'sum'),
    early_active_days=('date', 'nunique')
).reset_index()

print(early_learning_features.shape)
early_learning_features.head()

(29204, 5)

,code_module,code_presentation,id_student,early_total_clicks,early_active_days
0,AAA,2013J,11391,710,29
1,AAA,2013J,28400,986,50
2,AAA,2013J,30268,281,12
3,AAA,2013J,31604,1382,75
4,AAA,2013J,32885,799,47

In [54]:
final_early_data = student_info.merge(
    early_assessment_features,
    on=['code_module', 'code_presentation', 'id_student'],
    how='left'
)

final_early_data = final_early_data.merge(
    early_learning_features,
    on=['code_module', 'code_presentation', 'id_student'],
    how='left'
)

print(final_early_data.shape)
final_early_data.head()

(32593, 16)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,early_avg_score,early_assessment_count,early_total_clicks,early_active_days
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass,81.000000,3.0,710.0,29.0
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass,69.333333,3.0,986.0,50.0
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn,NaN,NaN,281.0,12.0
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass,72.333333,3.0,1382.0,75.0
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass,54.000000,3.0,799.0,47.0

In [55]:
final_early_data.isnull().sum()

code_module                  0
code_presentation            0
id_student                   0
gender                       0
region                       0
highest_education            0
imd_band                     0
age_band                     0
num_of_prev_attempts         0
studied_credits              0
disability                   0
final_result                 0
early_avg_score           6807
early_assessment_count    6784
early_total_clicks        3389
early_active_days         3389
dtype: int64

In [56]:
final_early_data.groupby('final_result')[
    ['early_avg_score', 'early_assessment_count', 'early_total_clicks', 'early_active_days']
].apply(lambda x: x.isnull().sum())

,early_avg_score,early_assessment_count,early_total_clicks,early_active_days
final_result,,,,
Distinction,1,1,2,2
Fail,1303,1300,383,383
Pass,17,17,10,10
Withdrawn,5486,5466,2994,2994

In [57]:
final_early_data[
    ['early_avg_score', 'early_assessment_count',
     'early_total_clicks', 'early_active_days']
].isnull().all(axis=1).value_counts()

False    29265
True      3328
Name: count, dtype: int64

In [58]:
final_early_data = final_early_data.dropna(
    subset=[
        'early_avg_score',
        'early_assessment_count',
        'early_total_clicks',
        'early_active_days'
    ],
    how='all'
)

print("New dataset shape:", final_early_data.shape)

New dataset shape: (29265, 16)

In [59]:
final_early_data.isnull().sum()

code_module                  0
code_presentation            0
id_student                   0
gender                       0
region                       0
highest_education            0
imd_band                     0
age_band                     0
num_of_prev_attempts         0
studied_credits              0
disability                   0
final_result                 0
early_avg_score           3479
early_assessment_count    3456
early_total_clicks          61
early_active_days           61
dtype: int64

In [60]:
final_early_data[
    final_early_data['early_avg_score'].isnull()
][[
    'final_result',
    'early_assessment_count',
    'early_total_clicks',
    'early_active_days'
]].head(10)

,final_result,early_assessment_count,early_total_clicks,early_active_days
2,Withdrawn,NaN,281.0,12.0
44,Withdrawn,NaN,57.0,10.0
118,Fail,NaN,59.0,8.0
136,Withdrawn,NaN,68.0,6.0
169,Fail,NaN,164.0,8.0
171,Withdrawn,NaN,198.0,7.0
209,Fail,NaN,58.0,2.0
227,Withdrawn,0.0,1228.0,27.0
243,Withdrawn,NaN,467.0,22.0
256,Withdrawn,NaN,420.0,3.0

In [61]:
# Missing assessment count means no early assessment record
final_early_data['early_assessment_count'] = (
    final_early_data['early_assessment_count'].fillna(0)
)

# Fill missing early average score with median
score_median = final_early_data['early_avg_score'].median()

final_early_data['early_avg_score'] = (
    final_early_data['early_avg_score'].fillna(score_median)
)

# Fill very few missing learning activity values with median
final_early_data['early_total_clicks'] = (
    final_early_data['early_total_clicks']
    .fillna(final_early_data['early_total_clicks'].median())
)

final_early_data['early_active_days'] = (
    final_early_data['early_active_days']
    .fillna(final_early_data['early_active_days'].median())
)

print("Missing values after handling:")
print(final_early_data.isnull().sum())

Missing values after handling:
code_module               0
code_presentation         0
id_student                0
gender                    0
region                    0
highest_education         0
imd_band                  0
age_band                  0
num_of_prev_attempts      0
studied_credits           0
disability                0
final_result              0
early_avg_score           0
early_assessment_count    0
early_total_clicks        0
early_active_days         0
dtype: int64

In [62]:
final_early_data['final_result'].value_counts()

final_result
Pass           12360
Withdrawn       7182
Fail            6700
Distinction     3023
Name: count, dtype: int64

In [63]:
features = final_early_data.drop(
    columns=['final_result', 'id_student']
)

target = final_early_data['final_result']

print("Features:")
print(features.columns.tolist())

print("\nTarget:")
print(target.name)

Features:
['code_module', 'code_presentation', 'gender', 'region', 'highest_education', 'imd_band', 'age_band', 'num_of_prev_attempts', 'studied_credits', 'disability', 'early_avg_score', 'early_assessment_count', 'early_total_clicks', 'early_active_days']

Target:
final_result

In [64]:
categorical_features = [
    'code_module',
    'code_presentation',
    'gender',
    'region',
    'highest_education',
    'imd_band',
    'age_band',
    'disability'
]

numerical_features = [
    'num_of_prev_attempts',
    'studied_credits',
    'early_avg_score',
    'early_assessment_count',
    'early_total_clicks',
    'early_active_days'
]

print("Categorical features:", categorical_features)
print("Numerical features:", numerical_features)

Categorical features: ['code_module', 'code_presentation', 'gender', 'region', 'highest_education', 'imd_band', 'age_band', 'disability']
Numerical features: ['num_of_prev_attempts', 'studied_credits', 'early_avg_score', 'early_assessment_count', 'early_total_clicks', 'early_active_days']

In [65]:
from sklearn.model_selection import train_test_split

# First split: 70% training, 30% temporary
X_train, X_temp, y_train, y_temp = train_test_split(
    features,
    target,
    test_size=0.30,
    random_state=42,
    stratify=target
)

# Second split: 15% validation, 15% test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

print("Training set:", X_train.shape)
print("Validation set:", X_val.shape)
print("Test set:", X_test.shape)

print("\nTarget distribution:")
print("Train:\n", y_train.value_counts())
print("\nValidation:\n", y_val.value_counts())
print("\nTest:\n", y_test.value_counts())

Training set: (20485, 14)
Validation set: (4390, 14)
Test set: (4390, 14)

Target distribution:
Train:
 final_result
Pass           8652
Withdrawn      5027
Fail           4690
Distinction    2116
Name: count, dtype: int64

Validation:
 final_result
Pass           1854
Withdrawn      1078
Fail           1005
Distinction     453
Name: count, dtype: int64

Test:
 final_result
Pass           1854
Withdrawn      1077
Fail           1005
Distinction     454
Name: count, dtype: int64

In [67]:
!git clone https://github.com/Sajib1099/ai-driven-personalized-learning.git

Cloning into 'ai-driven-personalized-learning'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.

In [68]:
%cd /content/ai-driven-personalized-learning

/content/ai-driven-personalized-learning

In [70]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean